apiVersion: v1
kind: Service
metadata:
 name: "{{ .Values.service.name }}-service"
 namespace: beta
 labels:
      app: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: service-port
  selector:
    app: {{ .Values.service.name }}
